[project]
name = "adaptive-echo-python"
version = "0.1.0"
description = "Python definitions for Adaptive Echo"
readme = "README.md"
authors = [
    { name = "Tripp Lyons", email = "tripplyons@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.4",
    "soundfile>=0.13.1",
    "torch>=2.9.0",
]

[build-system]
requires = ["uv_build>=0.9.7,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.0.0",
    "ruff>=0.14.4",
]
